controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#Index

app_index:
    path: /
    controller : App\Controller\IndexController::index

#Creche

app_creche:
    path: /creche
    controller: App\Controller\CrecheController::index

app_creche_lister:
    path: /creche/lister
    controller: App\Controller\CrecheController::lister

app_creche_consulter:
    path: /creche/consulter/{id}
    controller: App\Controller\CrecheController::consulter