controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#Index

app_index:
    path: /
    controller : App\Controller\IndexController::index

#Creche

app_creche:
    path: /creche
    controller: App\Controller\CrecheController::index

app_creche_lister:
    path: /creche/lister
    controller: App\Controller\CrecheController::lister

app_creche_consulter:
    path: /creche/consulter/{id}
    controller: App\Controller\CrecheController::consulter

app_creche_ajouter:
    path: /creche/ajouter
    controller: App\Controller\CrecheController::ajouter

app_creche_modifier:
    path: /creche/modifier/{id}
    controller: App\Controller\CrecheController::modifier

app_creche_supprimer:
    path: /creche/supprimer/{id}
    controller: App\Controller\CrecheController::supprimer

#Personnel

app_personnel:
    path: /personnel
    controller: App\Controller\PersonnelController::index

app_personnel_lister:
    path: /personnel/lister
    controller: App\Controller\PersonnelController::lister

app_personnel_consulter:
    path: /personnel/consulter/{id}
    controller: App\Controller\PersonnelController::consulter

app_personnel_ajouter:
    path: /personnel/ajouter
    controller: App\Controller\PersonnelController::ajouter

app_personnel_modifier:
    path: /personnel/modifier/{id}
    controller: App\Controller\PersonnelController::modifier

app_personnel_supprimer:
    path: /personnel/supprimer/{id}
    controller: App\Controller\PersonnelController::supprimer

#Avis

app_avis:
    path: /avis
    controller: App\Controller\AvisController::index

app_avis_lister:
    path: /avis/lister
    controller: App\Controller\AvisController::lister

app_avis_consulter:
    path: /avis/consulter/{id}
    controller: App\Controller\AvisController::consulter

app_avis_ajouter:
    path: /avis/ajouter
    controller: App\Controller\AvisController::ajouter

app_avis_modifier:
    path: /avis/modifier/{id}
    controller: App\Controller\AvisController::modifier

app_avis_supprimer:
    path: /avis/supprimer/{id}
    controller: App\Controller\AvisController::supprimer

#Projet Pedagogique

app_projet:
    path: /projet
    controller: App\Controller\ProjetController::index

app_projet_lister:
    path: /projet/lister
    controller: App\Controller\ProjetController::lister

app_projet_consulter:
    path: /projet/consulter/{id}
    controller: App\Controller\ProjetController::consulter

app_projet_ajouter:
    path: /projet/ajouter
    controller: App\Controller\ProjetController::ajouter

app_projet_modifier:
    path: /projet/modifier/{id}
    controller: App\Controller\ProjetController::modifier